name: Feature Branch Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'src/main/**'
      - 'pom.xml'

jobs:
  Build_Docker_Image_on_Push:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11.0.8'
          distribution: 'adopt'
          architecture: x64
      -
        name: Build Docker Image
        run: mvn spring-boot:build-image -f pom.xml
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      -
        name: Push Image to DockerHub Registry
        run: |
          IMAGE_ID=$(docker images rest -q)
          VERSION=feature
          docker tag $IMAGE_ID filefighter/rest:$VERSION
          docker push filefighter/rest:$VERSION
