name: Tests (Feature)

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'renovate/**'
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/featureTests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
          architecture: x64
      - name: Run Tests
        run: |
          mvn clean verify
