name: Tests (Master)

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/masterTests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.8'
          distribution: 'adopt'
          architecture: x64
      - name: Run Tests and update Sonar
        run: |
          mvn clean verify sonar:sonar -s ./settings.xml
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}
