name: Stable Release

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Build_Docker_Image_on_new_Tag:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v1          
      - 
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
          architecture: x64
      -
         name: run all tests
         run: mvn clean test -f pom.xml
      - 
        name: build image with docker
        run: mvn spring-boot:build-image -f pom.xml -P prod
      - 
        name: Log into DockerHub Registry
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u filefighter --password-stdin
      - 
        name: generate image tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Push image to DockerHub Registry
        run: |
          IMAGE_ID=$(docker images rest -q)
          VERSION=${{ steps.vars.outputs.tag }}
          docker tag $IMAGE_ID filefighter/rest:$VERSION
          docker push filefighter/rest:$VERSION
