name: Stable Release

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Build_Docker_Image_on_new_Tag:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11.0.8'
          distribution: 'adopt'
          architecture: x64
      -
        name: Build Docker Image
        run: mvn spring-boot:build-image -f pom.xml
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      -
        name: Generate Image Tag from Git Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Push Image to DockerHub Registry
        run: |
          IMAGE_ID=$(docker images rest -q)
          VERSION=${{ steps.vars.outputs.tag }}
          docker tag $IMAGE_ID filefighter/rest:$VERSION
          docker tag $IMAGE_ID filefighter/rest:stable
          docker push filefighter/rest:$VERSION
          docker push filefighter/rest:stable
