name: Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  Run_all_tests:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
          architecture: x64
      -
        name: Setup database for tests.
        run: |
          docker create -p 27017:27017 --name FileFighterDB mongo:latest
          docker start FileFighterDB
      -
        name: Run Tests and update Sonar
        run: mvn clean test sonar:sonar -X -s ./settings.xml
