name: Tests

on: [push,workflow_dispatch]

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
          architecture: x64
      - name: Run tests with maven.
        run: mvn -B test --file pom.xml